#* fill experiment info
experiment_name: MNIST-Generate-AE
trial_index: 9
trainer_name: AutoEncoderTrainer

use_cpu: false
gradient_accumulation_steps: 1
split_batches: true
log_metrics: true

#* model config
model:
  name: AutoEncoder
  params:
    encoder:
      input_dim: 1
      hidden_dims:
        - 16
        - 64
        - 128
      padding: 2
    decoder:
      output_dim: 1
      hidden_dims:
        - 128
        - 64
        - 16
      cropping: 28

  checkpoint_path: 

#* dataset config
dataset:
  train:
    name: MNIST
    params:
      root: "data"
      train: true
    
  eval:
    name: MNIST
    params:
      root: "data"
      train: false

#* training config
train:
  num_epochs: 100
  batch_size: 1024
  optimizer: Adam
  learning_rate: 0.001
  use_ema: false
  need_other_modes:
    - eval
  need_datasets:
    - train
  
  log_interval: 1 # step
  eval_interval: 10 # epoch
  save_interval: 10 # epoch

#* evaluating config
eval:
  batch_size: 20
  # need_other_modes:
  #   - null
  need_datasets:
    - eval
  num_sample: 10

#* sampling config
sample:
  size: 10

#* other flexible config
# ema:
#   decay: 0.9999
#   checkpoint_path: null