#* fill experiment info
experiment_name: MNIST-Generate-VQVAE
trial_index: 1
trainer_name: VqVaeTrainer

use_cpu: false
gradient_accumulation_steps: 1
split_batches: true
log_metrics: true

#* model config
model:
  name: VQVAE
  params:
    encoder:
      input_dim: 1
      output_dim: 1
      hidden_dims:
        - 16
        - 32
    decoder:
      input_dim: 1
      output_dim: 1
      hidden_dims:
        - 32
        - 16
    quantizer:
      codebook_dim: 1
      codebook_num: 128
      decay: 0.99
      reset_threshold: 0.01
      epsilon: 0.00001

  checkpoint_path: " "

#* dataset config
dataset:
  train:
    name: MNIST
    params:
      root: "data"
      train: true
    
  eval:
    name: MNIST
    params:
      root: "data"
      train: false

#* training config
train:
  num_epochs: 100
  batch_size: 1024
  optimizer: Adam
  learning_rate: 0.001
  use_ema: false
  need_other_modes:
    - eval
  need_datasets:
    - train

  loss:
    names: 
      - Recon
      - Commit
    weights: 
      - 1.0
      - 1.0
  metric_names:
    - Perplexity
  
  log_interval: 1 # step
  eval_interval: 10 # epoch
  save_interval: 10 # epoch

#* evaluating config
eval:
  batch_size: 20
  # need_other_modes:
  #   - null
  need_datasets:
    - eval
  metric_names: 
  num_sample: 10

#* sampling config
sample:
  size: 10

#* other flexible config
# ema:
#   decay: 0.9999
#   checkpoint_path: null